version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-stock-assistant-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/models:/app/models
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=sqlite:///./stock_assistant.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - ai-stock-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-stock-assistant-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
    depends_on:
      - backend
    networks:
      - ai-stock-network

# 网络配置
networks:
  ai-stock-network:
    driver: bridge 